name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy via rsync & ssh
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          ARGS: -rlgoDzvc -i --delete
          SSH_CMD_ARGS: -o ServerAliveInterval=1500
          SSH_PRIVATE_KEY: ${{ secrets.YANDEX_CLOUD_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.YANDEX_CLOUD_SSH_HOST }}
          REMOTE_USER: github-ci
          TARGET: /home/github-ci/LingvoFriend
          EXCLUDE: /.git, /**/.env, /node_modules
          SCRIPT_BEFORE_REQUIRED: true
          SCRIPT_BEFORE: |
            cd /home/github-ci/LingvoFriend
            sudo docker system prune
            sudo docker compose down
          SCRIPT_AFTER_REQUIRED: true
          SCRIPT_AFTER: |
            cd /home/github-ci/LingvoFriend
            sudo -E docker compose up -d --build
