name: Deploy
on:
  push:
    branches:
      - main
      - 47.CI # TODO remove before merging to main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy via rsync & ssh
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.YANDEX_CLOUD_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.YANDEX_CLOUD_SSH_HOST }}
          REMOTE_USER: github-ci
          # SCRIPT_BEFORE_REQUIRED: true
          # SCRIPT_BEFORE: |
          #   docker compose down
          # SCRIPT_AFTER_REQUIRED: true
          # SCRIPT_AFTER: |
          #   LINGVOFRIEND_TGBOT_TOKEN=${{ secrets.LINGVOFRIEND_TGBOT_TOKEN }} \
          #   LINGVOFRIEND_YANDEXGPT_API_KEY=${{ secrets.LINGVOFRIEND_YANDEXGPT_API_KEY }} \
          #   docker compose up -d --build
